<?php /* @var $block \Motive\Easymarketing\Block\System\Config\Collect */ ?>

    <script>
        require([
            'jquery',
            'prototype',
            'Magento_Ui/js/modal/modal',
            'Magento_Ui/js/modal/alert'
        ], function(jQuery, prototype, modal, alert) {

            var buttonSpan = jQuery('#verification_span');

            function callAlert(text) {
                alert({
                    title: jQuery.mage.__('Google Site Verification'),
                    content: text
                });
            }

            jQuery('#verification_button').click(function() {

                var options = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: jQuery.mage.__('Google Site Verification'),
                    buttons: [{
                        text: jQuery.mage.__('Yes'),
                        class: '',
                        click: function() {
                            this.closeModal();

                            var $modalParagraphs = jQuery('#verification-modal p');

                            new Ajax.Request('<?php echo $block->getVerificationUrl() ?>', {
                                loaderArea: true,
                                asynchronous: true,
                                method: 'GET',
                                onComplete: function(response) {
                                    var responseObj = JSON.parse(response.responseText);
                                    if(responseObj.status == 0) {
                                        callAlert(jQuery.mage.__('Wrong Access Token.'));
                                    } else if(responseObj.status == 1) {
                                        callAlert(responseObj.errors.join('<br>'));
                                    } else if(responseObj.status == 2) {
                                        jQuery('#googleverificationstatus').attr('src', '<?php echo $block->getSuccessImage() ?>');
                                        callAlert(jQuery.mage.__('Google Verification successful.'));
                                        $modalParagraphs.eq(0).hide();
                                        $modalParagraphs.eq(1).show();
                                    } else if(responseObj.status == 3) {
                                        jQuery('#googleverificationstatus').attr('src', '<?php echo $block->getFailImage() ?>');
                                        callAlert(jQuery.mage.__('Google Verification disabled.'));
                                        $modalParagraphs.eq(1).hide();
                                        $modalParagraphs.eq(0).show();
                                    }
                                }
                            });
                        }
                    }, {
                        text: jQuery.mage.__('No'),
                        class: '',
                        click: function() {
                            this.closeModal();
                        }
                    }]
                };

                var popup = modal(options, jQuery('#verification-modal'));

                jQuery('#verification-modal').modal('openModal');
            });

        });
    </script>

    <div id="verification-modal" style="display: none;">
        <p style="<?php if($block->getCurrentStatus()) echo 'display: none;' ?>"><?php echo __('I agree on adding emarketing as additional &quot;owner&quot; when enabling the Google Site Verification. This is required for authorizing emarketing to import my product data through the API. Of course I can revoke this consent at any time. Under no circumstances will emarketing use, share or save my data for purposes other than my campaign control.<br><br>When performing the verification, the Magento Cache will be flushed.'); ?></p>
        <p style="<?php if(!$block->getCurrentStatus()) echo 'display: none;' ?>"><?php echo __('When the Verification is revoked, the Magento Cache will be flushed.'); ?></p>
    </div>
<?php echo $block->getButtonHtml() ?>
<span style="display: inline-block; width: 20px; height: 20px; position: relative; top: 3px; left: 10px;"><img id="googleverificationstatus" src="<?php echo $block->getCurrentStatusImage() ?>"></span>
